### ISSUE TITLE
[iOS] 서버로 받은 이슈 목록을 확인할 수 있다 - 1

### ISSUE THREAD

**Issue by raindropiOS** [sjuhan123/issue-tracker#26]
# 기능 요구사항
Sever로부터 받은 이슈 목록 확인 

# 요구 세부사항
- [x] : 타이틀부터 라벨까지 선언한 모델을 뷰에 담을 수 있다
- [ ] : 라벨과 함께 받은 색상을 라벨에 적용할 수 있다

## TASK 단위
- [x] : json 파싱해서 Data 모델에 담기

커밋이 길어져 develop-iOS에 머지 진행 후 다음 이슈에서 이어 진행하겠습니다
